sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE="Dockerfile.travis" PYTHON="python3"

before_install:
  - docker build -t lmp -f "$DOCKER_FILE" .
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach lmp bash > container_id
  - cat container_id

install:
  - docker exec "$(cat container_id)" pip3 install app
script:
  # run our tests in the running contained
  - docker exec "$(cat container_id)" xvfb-run -a lmview

after_script:
  # stop the container
  - docker stop "$(cat container_id)"
