sudo: required
services: docker
language: generic


install:
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach --name straintables gab0/python3-gtk3-scipy:v1
  - docker exec straintables git clone https://github.com/Gab0/straintables.git /app/straintables
  - docker exec straintables pip install /app/straintables

script:
  - docker exec straintables lmpline --help
after_script:
  - docker stop straintables
