sudo: required
services: docker
language: generic


install:
  - docker run --volume "$TRAVIS_BUILD_DIR:/app/straintables" --workdir "/app/straintables" --tty --detach --name straintables gab0/python3-gtk3-scipy:v2
  - docker exec straintables apk add tree
  - docker exec straintables tree -d / -L 3
  - docker exec straintables pip install /app/straintables

script:
  - docker exec straintables stpline --help
  - docker exec straintables xvfb-run stview --help
  # Travis machine just won't download from FTP, so disabling this for now.
  #- docker exec straintables xvfb-run python /app/straintables/test/PipelineTest.py
after_script:
  - docker stop straintables
