sudo: required
services: docker
language: generic


env:
  - DOCKER_FILE="Dockerfile" PYTHON="python3"

install:
  - docker build -t lmp -f "$DOCKER_FILE" .
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach lmp > container_id
  - ID=$(cat container_id)
  - docker exec "$(cat container_id)" pip3 install /app

script:
  - docker exec "$(cat container_id)" lmpline --help
after_script:
  - docker stop "$(cat container_id)"
