sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE="Dockerfile.travis" PYTHON="python3"

before_install:
  # Create a docker image called "myimage"
  - docker build -t lmp -f "$DOCKER_FILE" .

before_script:
  # create a docker container from the image, mount the current working
  # directory to /app inside the container and let the container running
  # in the background. The resulting container ID will be saved to
  # container_id so we can reference it later on.
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach myimage bash > container_id

install:
  - docker exec "$(cat container_id)" pip3 install app
script:
  # run our tests in the running contained
  - docker exec "$(cat container_id)" xvfb-run -a lmview

after_script:
  # stop the container
  - docker stop "$(cat container_id)"
