sudo: required
services: docker
language: generic


install:
  - docker run --volume "$(pwd)/Gab0/straintables:/app/straintables" --workdir "/app/straintables" --tty --detach --name straintables gab0/python3-gtk3-scipy:v2
  - docker exec tree -d / -L 2
  - docker exec straintables pip install .

script:
  - docker exec straintables lmpline --help
after_script:
  - docker stop straintables
