sudo: required
services: docker
language: generic


install:
  - docker run --volume "/root/Gab0/straintables:/app/straintables" --workdir "/app/straintables" --tty --detach --name straintables gab0/python3-gtk3-scipy:v2
  - ls /root
  - docker exec straintables apk add tree
  - docker exec straintables tree -d / -L 3
  - docker exec straintables pip install /app/straintables

script:
  - docker exec straintables lmpline --help
after_script:
  - docker stop straintables
